language: cpp
dist: trusty
services:
  - docker
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew update
      brew install jsoncpp argtable curl hiredis redis ninja wget lcov gcovr
      brew install libmicrohttpd --with-ssl
      mkdir -p /usr/local/include/catch
      wget -O /usr/local/include/catch/catch.hpp https://github.com/catchorg/Catch2/releases/download/v2.2.3/catch.hpp
    fi

matrix:
  include:
    - env: OS=fedora
      os: linux
    - env: OS=arch
      os: linux
    - env: OS=debian9
      os: linux
    - env: OS=debian10
      os: linux
    - env: OS=ubuntu1604
      os: linux
    - env: OS=ubuntu1804
      os: linux
    - env: OS=osx
      os: osx
      compiler: clang

script:
    - cd docker && make ${OS};
    - cd build && make coverage
    - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
      fi
